/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatesRouteImport } from './routes/states'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as FoodsRouteImport } from './routes/foods'
import { Route as FestivalsRouteImport } from './routes/festivals'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatesSlugRouteImport } from './routes/states_.$slug'
import { Route as InterestsSlugRouteImport } from './routes/interests.$slug'
import { Route as FoodsSlugRouteImport } from './routes/foods_.$slug'
import { Route as FestivalsSlugRouteImport } from './routes/festivals_.$slug'
import { Route as DestinationsSlugRouteImport } from './routes/destinations_.$slug'

const StatesRoute = StatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsRoute = FoodsRouteImport.update({
  id: '/foods',
  path: '/foods',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalsRoute = FestivalsRouteImport.update({
  id: '/festivals',
  path: '/festivals',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesSlugRoute = StatesSlugRouteImport.update({
  id: '/states_/$slug',
  path: '/states/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestsSlugRoute = InterestsSlugRouteImport.update({
  id: '/interests/$slug',
  path: '/interests/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsSlugRoute = FoodsSlugRouteImport.update({
  id: '/foods_/$slug',
  path: '/foods/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalsSlugRoute = FestivalsSlugRouteImport.update({
  id: '/festivals_/$slug',
  path: '/festivals/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/destinations_/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/festivals': typeof FestivalsRoute
  '/foods': typeof FoodsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/states': typeof StatesRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/festivals/$slug': typeof FestivalsSlugRoute
  '/foods/$slug': typeof FoodsSlugRoute
  '/interests/$slug': typeof InterestsSlugRoute
  '/states/$slug': typeof StatesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/festivals': typeof FestivalsRoute
  '/foods': typeof FoodsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/states': typeof StatesRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/festivals/$slug': typeof FestivalsSlugRoute
  '/foods/$slug': typeof FoodsSlugRoute
  '/interests/$slug': typeof InterestsSlugRoute
  '/states/$slug': typeof StatesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/festivals': typeof FestivalsRoute
  '/foods': typeof FoodsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/states': typeof StatesRoute
  '/destinations_/$slug': typeof DestinationsSlugRoute
  '/festivals_/$slug': typeof FestivalsSlugRoute
  '/foods_/$slug': typeof FoodsSlugRoute
  '/interests/$slug': typeof InterestsSlugRoute
  '/states_/$slug': typeof StatesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/destinations'
    | '/festivals'
    | '/foods'
    | '/search'
    | '/sitemap.xml'
    | '/states'
    | '/destinations/$slug'
    | '/festivals/$slug'
    | '/foods/$slug'
    | '/interests/$slug'
    | '/states/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/destinations'
    | '/festivals'
    | '/foods'
    | '/search'
    | '/sitemap.xml'
    | '/states'
    | '/destinations/$slug'
    | '/festivals/$slug'
    | '/foods/$slug'
    | '/interests/$slug'
    | '/states/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/destinations'
    | '/festivals'
    | '/foods'
    | '/search'
    | '/sitemap.xml'
    | '/states'
    | '/destinations_/$slug'
    | '/festivals_/$slug'
    | '/foods_/$slug'
    | '/interests/$slug'
    | '/states_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRoute
  FestivalsRoute: typeof FestivalsRoute
  FoodsRoute: typeof FoodsRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatesRoute: typeof StatesRoute
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  FestivalsSlugRoute: typeof FestivalsSlugRoute
  FoodsSlugRoute: typeof FoodsSlugRoute
  InterestsSlugRoute: typeof InterestsSlugRoute
  StatesSlugRoute: typeof StatesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/states': {
      id: '/states'
      path: '/states'
      fullPath: '/states'
      preLoaderRoute: typeof StatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods': {
      id: '/foods'
      path: '/foods'
      fullPath: '/foods'
      preLoaderRoute: typeof FoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festivals': {
      id: '/festivals'
      path: '/festivals'
      fullPath: '/festivals'
      preLoaderRoute: typeof FestivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states_/$slug': {
      id: '/states_/$slug'
      path: '/states/$slug'
      fullPath: '/states/$slug'
      preLoaderRoute: typeof StatesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interests/$slug': {
      id: '/interests/$slug'
      path: '/interests/$slug'
      fullPath: '/interests/$slug'
      preLoaderRoute: typeof InterestsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods_/$slug': {
      id: '/foods_/$slug'
      path: '/foods/$slug'
      fullPath: '/foods/$slug'
      preLoaderRoute: typeof FoodsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festivals_/$slug': {
      id: '/festivals_/$slug'
      path: '/festivals/$slug'
      fullPath: '/festivals/$slug'
      preLoaderRoute: typeof FestivalsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations_/$slug': {
      id: '/destinations_/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRoute,
  FestivalsRoute: FestivalsRoute,
  FoodsRoute: FoodsRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatesRoute: StatesRoute,
  DestinationsSlugRoute: DestinationsSlugRoute,
  FestivalsSlugRoute: FestivalsSlugRoute,
  FoodsSlugRoute: FoodsSlugRoute,
  InterestsSlugRoute: InterestsSlugRoute,
  StatesSlugRoute: StatesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
